// react-app/src/pages/login/login.js
import React, { useState, useEffect } from "react";
import { doLogin, reqLoginError, reqLoggedIn } from "./../../slices/userSlice";
import { useDispatch, useSelector } from "react-redux";

export function Login() {
  const [email, setEmail] = useState();
  const [password, setPassword] = useState();
  const [isNotValid, setIsNotValid] = useState(false);
  const [serverError, setServerError] = useState(false);
  const dispatch = useDispatch();
  const serverErrorSelector = useSelector(reqLoginError);
  const serverIsLoggedIn = useSelector(reqLoggedIn);

  const login = () => {
    const data = {
      email,
      password,
    };
    dispatch(doLogin(data));
  };

  useEffect(() => {
    setServerError(serverErrorSelector);
    setIsNotValid(!(email && password));

    if (serverIsLoggedIn) {
      console.log("Redirect ...");
    }
  }, [email, password, serverErrorSelector, serverIsLoggedIn]);

  return (
    <>
      <h1>LOGIN</h1>
      {isNotValid && (
        <div className="alert alert-danger">
          Email and password are required
        </div>
      )}

      {serverError && (
        <div className="alert alert-danger">
          Server Error: email or password is invalid
        </div>
      )}
      <input
        type="text"
        className="form-control"
        placeholder="Email ..."
        onChange={(event) => setEmail(event.target.value)}
        value={email}
      />
      <input
        type="password"
        className="form-control"
        placeholder="Password ..."
        onChange={(event) => setPassword(event.target.value)}
        value={password}
      />
      <button className="btn btn-success" disabled={isNotValid} onClick={login}>
        Login
      </button>
    </>
  );
}

// angular-app/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MainService } from 'src/app/services/main.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent implements OnInit {
  public loginForm: FormGroup;
  public submitted: boolean = false;
  public serverError: boolean = false;
  constructor(
    private formBuilder: FormBuilder,
    private mainService: MainService
  ) {}

  ngOnInit(): void {
    this.loginForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]],
    });
  }

  doLogin() {
    console.log(this.loginForm);
    this.submitted = true;
    this.serverError = false;

    if (this.loginForm.status === 'VALID') {
      this.mainService.login(this.loginForm.value).subscribe(
        (res) => {
          console.log('Redirect ...');
        },
        (err) => {
          if (err) {
            this.serverError = true;
          }
        }
      );
    }
  }

  get f() {
    return this.loginForm.controls;
  }
}

<h1>Login</h1>
<div class="alert alert-danger" *ngIf="serverError">
  Email or password is invalid
</div>
<form [formGroup]="loginForm" (ngSubmit)="doLogin()">
  <div class="form-group">
    <label>Email</label>
    <input
      class="form-control"
      placeholder="Email ..."
      formControlName="email"
    />

    <div *ngIf="submitted && f.email.errors">
      <p *ngIf="f.email.errors.required">Email is required</p>
      <p *ngIf="f.email.errors.email">Email is not valid</p>
    </div>
  </div>
  <div class="form-group">
    <label>Password</label>
    <input
      class="form-control"
      type="password"
      placeholder="Password ..."
      formControlName="password"
    />
  </div>
  <button
    type="submit"
    class="btn btn-success"
    [disabled]="loginForm.status === 'INVALID'"
  >
    Login
  </button>
</form>
