// react-app/src/pages/register/register.js
import React, { useState, useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import {
  doRegister,
  reqRegisterData,
  clearRegisterData,
  userSlice,
} from "./../../slices/userSlice";
import { useHistory } from "react-router-dom";

// name email password confirm_password
export function Register() {
  const [name, setName] = useState();
  const [email, setEmail] = useState();
  const [password, setPassword] = useState();
  const [confirm_password, setConfirmPassword] = useState();
  const [isValid, setIsValid] = useState(false);
  const dispatch = useDispatch();
  const history = useHistory();

  const registerResponse = useSelector(reqRegisterData);

  useEffect(() => {
    if (registerResponse && registerResponse._id) {
      history.push("/login");
      dispatch(clearRegisterData());
    }
    setIsValid(!(name && email && password && confirm_password));
  }, [registerResponse, name, email, password, confirm_password]);

  const register = () => {
    const data = {
      name,
      email,
      passwords: {
        password,
        confirm_password,
      },
    };

    console.log(data);
    if (!isValid) dispatch(doRegister(data));
  };

  return (
    <>
      <h1>REGISTER</h1>
      {isValid && <div className="alert alert-danger">Formul este invalid</div>}

      {isValid ? (
        <div className="alert alert-danger">Formul este invalid</div>
      ) : (
        <div className="alert alert-success">Formul este valid</div>
      )}

      <input
        type="text"
        className="form-control"
        placeholder="Name ..."
        onChange={(event) => setName(event.target.value)}
        value={name}
      />
      <input
        type="text"
        className="form-control"
        placeholder="Email ..."
        onChange={(event) => setEmail(event.target.value)}
        value={email}
      />
      <input
        type="password"
        className="form-control"
        placeholder="Password ..."
        onChange={(event) => setPassword(event.target.value)}
        value={password}
      />
      <input
        type="password"
        className="form-control"
        placeholder="Confirm Password ..."
        onChange={(event) => setConfirmPassword(event.target.value)}
        value={confirm_password}
      />

      <button className="btn btn-success" disabled={isValid} onClick={register}>
        Register
      </button>
    </>
  );
}

// angular-app/src/app/pages/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { MainService } from 'src/app/services/main.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent implements OnInit {
  public user: any = {};
  constructor(private mainService: MainService, private router: Router) {}

  ngOnInit(): void {}

  register() {
    console.log(this.user);
    const { name, email, password, confirm_password } = this.user;
    const data = {
      name,
      email,
      passwords: {
        password,
        confirm_password,
      },
    };

    this.mainService.register(data).subscribe((res) => {
      console.log(res);
      if (res && res.doc._id) {
        this.router.navigate(['/login']);
      }
    });
  }

  isValid() {
    const { name, email, password, confirm_password } = this.user;
    return !(name && email && password && confirm_password);
  }

  validateEmail(mail: string) {
    if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(mail)) {
      return true;
    }
    return false;
  }
}

<h2>Register</h2>
<div class="alert alert-danger" *ngIf="isValid()">Your form is invalid</div>
<input class="form-control" placeholder="Name ..." [(ngModel)]="user.name" />
<input
  class="form-control"
  [class]="
    validateEmail(user.email) ? 'form-control' : 'form-control is-invalid'
  "
  [ngClass]="validateEmail(user.email) ? '' : 'is-invalid'"
  placeholder="Email ..."
  [(ngModel)]="user.email"
/>
<input
  class="form-control"
  type="password"
  placeholder="Password ..."
  [(ngModel)]="user.password"
/>
<input
  class="form-control"
  type="password"
  placeholder="Confirm Password ..."
  [(ngModel)]="user.confirm_password"
/>

<button class="btn btn-primary" [disabled]="isValid()" (click)="register()">
  Register
</button>
